### ISSUE TITLE
NoLoadingTerrain 1.21.1 Support

### ISSUE THREAD

**Issue by Meolsei** [codingcat2468/NoLoadingTerrain#1]
Despite Modrinth's mention of the mod [supporting 1.21.1](https://github.com/user-attachments/assets/9afd86ca-44c3-4618-b0af-9ef59304f51f), Fabric throws an error and prevents the mod from loading.

**Comment by codingcat2468** [comment]
Thanks for letting me know, it seems like modrinth automatically marks 1.21 compatible mods as 1.21.1 compatible, without actually checking if the mod supports it. I just released a new version specifically for 1.21.1 and fixed the compatibillity data on the 1.21 version, let me know if you run into any other issues!

**Comment by Meolsei** [comment]
I appreciate it! In the meantime, I simply edited the mod directly and
changed the mod version to 1.21.1, lol.
